const PREFIX = 'LESSON_LIST';

export const TOGGLE_EXPANEL_BY_CLASS = `${PREFIX}_TOGGLE_EXPANEL_BY_CLASS`;
export const FETCH_VOCABULARIES_SUCCESS = 'FETCH_VOCABULARIES_SUCCESS';
export const SAVE_VOCABULARY_SUCCESS = 'SAVE_VOCABULARY_SUCCESS';
export const DELETE_VOCABULARY_SUCCESS = 'DELETE_VOCABULARY_SUCCESS';
export const SHOW_VOCABULARY_MESSAGE = 'SHOW_VOCABULARY_MESSAGE';
export const WAIT_VOCABULARY_ACTION = 'WAIT_VOCABULARY_ACTION';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_SUCCESS_USER = 'UPDATE_SUCCESS_USER';
export const UPDATE_ERROR_USER = 'UPDATE_ERROR_USER';